### ISSUE TITLE
Build failing during "Build Codeplugs" step

### ISSUE THREAD

**Issue by MaxBMitchell** [mycodeplug/example-codeplug#16]
I've attached the annotations file which appears to cite the issue.  Looks like the following URL is not found: 
https://pnwdigital.net/files/acb/PNW_Digital_Repeaters.zip .

[7_Build Codeplugs.txt](https://github.com/mycodeplug/example-codeplug/files/8056874/7_Build.Codeplugs.txt)

**Comment by masenf** [comment]
@MaxBMitchell Thanks for reporting this issue. PNWDigital has recently redesigned their website and it appears the link is now broken.

I have reached out to their admin team for assistance and will await their reply.

I don't see any mirrors for the file immediately, and I can't find a recent copy on my machine today. If they haven't restored the link by tomorrow, I'll mirror it myself in the meantime.

Ball's in my/PNWD's court.

**Comment by masenf** [comment]
@MaxBMitchell I didn't hear anything from PNWD admin team yet; The latest versions of the files that I could find are from two weeks ago: https://github.com/mycodeplug/dzcb/blob/b0083a5654f173a36671f90e8734982a01d16fad/codeplug/mirror/PNW_Digital_Repeaters_2022-01-30.zip

I've went ahead and pushed `dzcb-0.3.5` which automatically falls back to _my_ mirror when the PNWDigital "upstream" file isn't available. This should at least unblock builds when PNWDigital is down, even if the data is the most current.

I'm going to ask you to give it another shot with the new version and see if you can proceed. I'll continue to follow up with PNWD about where the file got off to.

**Comment by masenf** [comment]
Alright, mystery solved; the files got moved here https://pnwdigital.net/files/. And the repeaters zip that we care about is now at https://pnwdigital.net/wp-content/files/acb/PNW_Digital_Repeaters.zip.

I updated dzcb to look in that spot and it seems to be working fully now. Will close this issue, please reopen if you continue to have problems.

https://github.com/mycodeplug/dzcb/releases/tag/0.3.6
